{
    "data_folder_path": "data/CVE-2019-13111",
    "pull_requests_urls": [
        "https://github.com/Exiv2/exiv2/pull/797"
    ],
    "cve_name": "CVE-2019-13111",
    "repo": "Exiv2/exiv2",
    "warnings": {
        "cve": "CVE-2019-13111",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "test/data/issue_791_poc1.webp",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            },
            {
                "type": "NO_PATCH",
                "file_name": "test/data/issue_791_poc1.webp",
                "message": "File has no patch data.\n"
            },
            {
                "type": "NOT_MODIFIED",
                "file_name": "tests/bugfixes/github/test_issue_791.py",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".cpp": 1,
        ".py": 1,
        ".hpp": 1
    },
    "file_number": 3,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 88,
    "private_key_files": [],
    "languages": [
        "Python",
        "Cpp"
    ]
}