{
    "data_folder_path": "data/CVE-2020-29128",
    "pull_requests_urls": [
        "https://github.com/petl-developers/petl/pull/527"
    ],
    "cve_name": "CVE-2020-29128",
    "repo": "petl-developers/petl",
    "warnings": {
        "cve": "CVE-2020-29128",
        "warnings": []
    },
    "files_extension_stats": {
        ".py": 2,
        ".rst": 1
    },
    "file_number": 3,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 332,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}