{
    "data_folder_path": "data/CVE-2020-26891",
    "pull_requests_urls": [
        "https://github.com/matrix-org/synapse/pull/8444"
    ],
    "cve_name": "CVE-2020-26891",
    "repo": "matrix-org/synapse",
    "warnings": {
        "cve": "CVE-2020-26891",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "changelog.d/8444.bugfix",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            },
            {
                "type": "NOT_MODIFIED",
                "file_name": "synapse/res/templates/auth_success.html",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            },
            {
                "type": "NOT_MODIFIED",
                "file_name": "synapse/res/templates/recaptcha.html",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            },
            {
                "type": "NOT_MODIFIED",
                "file_name": "synapse/res/templates/terms.html",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".html": 3,
        ".py": 5,
        ".bugfix": 1
    },
    "file_number": 9,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 237,
    "private_key_files": [],
    "languages": [
        "Python",
        "HTML"
    ]
}